/**
 * Use this file to configure your truffle project.
 */

// require('dotenv').config();
// const { MNEMONIC, PROJECT_ID } = process.env;

// const HDWalletProvider = require('@truffle/hdwallet-provider');

module.exports = {
  /**
   * Networks configuration defines how you connect to your Ethereum client.
   */

  networks: {
    // Configuration for the local development network (e.g., Ganache or local Geth node).
    development: {
      host: "127.0.0.1", // Localhost (default: none)
      port: 7545,        // Standard Ethereum port (default: none)
      network_id: "*",   // Match any network id (default: none)
    },
  },

  // Set default mocha options here, use special reporters, etc.
  mocha: {
    // timeout: 100000
  },

  /**
   * Configure your compilers
   * This is the critical section for resolving the "invalid opcode" error.
   */
  compilers: {
    solc: {
      version: "0.8.21", // Ensures Truffle uses the exact version matching your contract's pragma
      // docker: true,
      settings: {
        optimizer: {
          enabled: true, // It's generally good practice to enable the optimizer
          runs: 200
        },
        // IMPORTANT FIX: 
        // Set the EVM version to 'berlin' to ensure the bytecode 
        // generated by solc 0.8.21 is compatible with Ganache.
        evmVersion: "berlin" 
      }
    }
  },

  // Truffle DB is currently disabled by default...
  db: {
    enabled: false,
    // host: "127.0.0.1",
    // adapter: {
    //   name: "indexeddb",
    //   settings: {
    //     directory: ".db"
    //   }
    // }
  }
};